// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucgeffmwzzqgdzbykmql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZ2VmZm13enpxZ2R6YnlrbXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDU3MTgsImV4cCI6MjA2ODUyMTcxOH0.MyU0E2_HYHc2AOcZ5yJLk0ykjn8_QH0y5_OxNjXI444";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});